title:              NolansBlogs
tagline:            Accurate, Curated
description:        Global, Local & International News.
url:                http://scannerradio.github.io

author:
  name:             Nolan Tanzman
  url:              https://twitter.com/JewHefner_
  email:            ClearlyElevated@iCloud.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
